.TH QCMA 1 "MARCH 2015"
.SH NAME
qcma \- Content manager for the PlayStation Vita
.SH SYNOPSIS
.B qcma

.SH DESCRIPTION
\fBqcma\fR is a cross-platform application to provide an Open Source implementation
of the original Content Manager Assistant that comes with the PS Vita.
.TP
Qcma will let you backup your games, songs, photos & videos via USB or wireless.

.SH "SEE ALSO"
.I /usr/share/doc/qcma/README.md
